//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NUSMed_WebApp.Admin.Manage_Accounts
{


    public partial class Manage_Researcher_Data
    {
    }
}
